### ISSUE TITLE
UX: Add some examples

### ISSUE THREAD

**Issue by ful09003** [ful09003/cards#5]
Hello friends cloning/checking out Proxl!

I'll add some examples but here's a `cards.yml` that can be used to get started (it's what I've been using, anyways):

```
---
output: table
scorers:
  - name: MAC addresses are discouraged
    description: "MAC addresses tend to be high cardinality in our environment; if not strictly needed drop this label"
    criticality: 3 # In our fictional scenario, UUIDs are more critically 'bad'
    scoring-method:
      type: regex_scorer
      criteria:
        - "^[a-fA-F0-9]{2}(:[a-fA-F0-9]{2}){5}$"
  - name: Exceptionally lengthy metrics are discouraged
    description: "Metrics with more than 4 labels tend to not do well in our environment; drop unnecessary labels"
    criticality: 3
    scoring-method:
      type: label_length_scorer
      criteria:
        - 4
  - name: Exclude problematic metric families
    description: "Certain metrics are known to cause confusion to users; these metrics should only be accepted if they are well-understood"
    criticality: 4
    scoring-method:
      type: family_name_scorer
      criteria:
        - node_hwmon_chip_names
        - node_cpu_scaling_frequency_max_hertz
```
